name: Multiarch CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  testalpine:
    runs-on: ubuntu-latest
    name: Test JDK 8
    strategy:
      fail-fast: false
      matrix:
        arch: [ armv6, armv7, aarch64, s390x, ppc64le ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Test on Alpine
        id: test-alpine
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: alpine_latest
          install: |
            apk update
            apk add maven musl
          run: sudo mvn test -B -Djacoco.skip=true

